package representations

type Realm struct {
	AccessCodeLifespan                            int32                    `json:"accessCodeLifespan,omitempty"`
	AccessCodeLifespanLogin                       int32                    `json:"accessCodeLifespanLogin,omitempty"`
	AccessCodeLifespanUserAction                  int32                    `json:"accessCodeLifespanUserAction,omitempty"`
	AccessTokenLifespan                           int32                    `json:"accessTokenLifespan,omitempty"`
	AccessTokenLifespanForImplicitFlow            int32                    `json:"accessTokenLifespanForImplicitFlow,omitempty"`
	AccountTheme                                  string                   `json:"accountTheme,omitempty"`
	ActionTokenGeneratedByAdminLifespan           int32                    `json:"actionTokenGeneratedByAdminLifespan,omitempty"`
	ActionTokenGeneratedByUserLifespan            int32                    `json:"actionTokenGeneratedByUserLifespan,omitempty"`
	AdminEventsDetailsEnabled                     *bool                    `json:"adminEventsDetailsEnabled,omitempty"`
	AdminEventsEnabled                            *bool                    `json:"adminEventsEnabled,omitempty"`
	AdminTheme                                    string                   `json:"adminTheme,omitempty"`
	Attributes                                    Map                      `json:"attributes,omitempty"`
	AuthenticationFlows                           []AuthenticationFlow     `json:"authenticationFlows,omitempty"`
	AuthenticatorConfig                           []AuthenticatorConfig    `json:"authenticatorConfig,omitempty"`
	BrowserFlow                                   string                   `json:"browserFlow,omitempty"`
	BrowserSecurityHeaders                        Map                      `json:"browserSecurityHeaders,omitempty"`
	BruteForceProtected                           *bool                    `json:"bruteForceProtected,omitempty"`
	ClientAuthenticationFlow                      string                   `json:"clientAuthenticationFlow,omitempty"`
	ClientScopeMappings                           Map                      `json:"clientScopeMappings,omitempty"`
	ClientScopes                                  []ClientScope            `json:"clientScopes,omitempty"`
	Clients                                       []Client                 `json:"clients,omitempty"`
	Components                                    MultiValuedHashMap       `json:"components,omitempty"`
	DefaultDefaultClientScopes                    []string                 `json:"defaultDefaultClientScopes,omitempty"`
	DefaultGroups                                 []string                 `json:"defaultGroups,omitempty"`
	DefaultLocale                                 string                   `json:"defaultLocale,omitempty"`
	DefaultOptionalClientScopes                   []string                 `json:"defaultOptionalClientScopes,omitempty"`
	DefaultRoles                                  []string                 `json:"defaultRoles,omitempty"`
	DefaultSignatureAlgorithm                     string                   `json:"defaultSignatureAlgorithm,omitempty"`
	DirectGrantFlow                               string                   `json:"directGrantFlow,omitempty"`
	DisplayName                                   string                   `json:"displayName,omitempty"`
	DisplayNameHtml                               string                   `json:"displayNameHtml,omitempty"`
	DockerAuthenticationFlow                      string                   `json:"dockerAuthenticationFlow,omitempty"`
	DuplicateEmailsAllowed                        *bool                    `json:"duplicateEmailsAllowed,omitempty"`
	EditUsernameAllowed                           *bool                    `json:"editUsernameAllowed,omitempty"`
	EmailTheme                                    string                   `json:"emailTheme,omitempty"`
	Enabled                                       *bool                    `json:"enabled,omitempty"`
	EnabledEventTypes                             []string                 `json:"enabledEventTypes,omitempty"`
	EventsEnabled                                 *bool                    `json:"eventsEnabled,omitempty"`
	EventsExpiration                              int64                    `json:"eventsExpiration,omitempty"`
	EventsListeners                               []string                 `json:"eventsListeners,omitempty"`
	FailureFactor                                 int32                    `json:"failureFactor,omitempty"`
	FederatedUsers                                []User                   `json:"federatedUsers,omitempty"`
	Groups                                        []Group                  `json:"groups,omitempty"`
	Id                                            string                   `json:"id,omitempty"`
	IdentityProviderMappers                       []IdentityProviderMapper `json:"identityProviderMappers,omitempty"`
	IdentityProviders                             []IdentityProvider       `json:"identityProviders,omitempty"`
	InternationalizationEnabled                   *bool                    `json:"internationalizationEnabled,omitempty"`
	KeycloakVersion                               string                   `json:"keycloakVersion,omitempty"`
	LoginTheme                                    string                   `json:"loginTheme,omitempty"`
	LoginWithEmailAllowed                         *bool                    `json:"loginWithEmailAllowed,omitempty"`
	MaxDeltaTimeSeconds                           int32                    `json:"maxDeltaTimeSeconds,omitempty"`
	MaxFailureWaitSeconds                         int32                    `json:"maxFailureWaitSeconds,omitempty"`
	MinimumQuickLoginWaitSeconds                  int32                    `json:"minimumQuickLoginWaitSeconds,omitempty"`
	NotBefore                                     int32                    `json:"notBefore,omitempty"`
	OfflineSessionIdleTimeout                     int32                    `json:"offlineSessionIdleTimeout,omitempty"`
	OfflineSessionMaxLifespan                     int32                    `json:"offlineSessionMaxLifespan,omitempty"`
	OfflineSessionMaxLifespanEnabled              *bool                    `json:"offlineSessionMaxLifespanEnabled,omitempty"`
	OtpPolicyAlgorithm                            string                   `json:"otpPolicyAlgorithm,omitempty"`
	OtpPolicyDigits                               int32                    `json:"otpPolicyDigits,omitempty"`
	OtpPolicyInitialCounter                       int32                    `json:"otpPolicyInitialCounter,omitempty"`
	OtpPolicyLookAheadWindow                      int32                    `json:"otpPolicyLookAheadWindow,omitempty"`
	OtpPolicyPeriod                               int32                    `json:"otpPolicyPeriod,omitempty"`
	OtpPolicyType                                 string                   `json:"otpPolicyType,omitempty"`
	OtpSupportedApplications                      []string                 `json:"otpSupportedApplications,omitempty"`
	PasswordPolicy                                string                   `json:"passwordPolicy,omitempty"`
	PermanentLockout                              *bool                    `json:"permanentLockout,omitempty"`
	ProtocolMappers                               []ProtocolMapper         `json:"protocolMappers,omitempty"`
	QuickLoginCheckMilliSeconds                   int64                    `json:"quickLoginCheckMilliSeconds,omitempty"`
	Realm                                         string                   `json:"realm,omitempty"`
	RefreshTokenMaxReuse                          int32                    `json:"refreshTokenMaxReuse,omitempty"`
	RegistrationAllowed                           *bool                    `json:"registrationAllowed,omitempty"`
	RegistrationEmailAsUsername                   *bool                    `json:"registrationEmailAsUsername,omitempty"`
	RegistrationFlow                              string                   `json:"registrationFlow,omitempty"`
	RememberMe                                    *bool                    `json:"rememberMe,omitempty"`
	RequiredActions                               []RequiredActionProvider `json:"requiredActions,omitempty"`
	ResetCredentialsFlow                          string                   `json:"resetCredentialsFlow,omitempty"`
	ResetPasswordAllowed                          *bool                    `json:"resetPasswordAllowed,omitempty"`
	RevokeRefreshToken                            *bool                    `json:"revokeRefreshToken,omitempty"`
	Roles                                         Roles                    `json:"roles,omitempty"`
	ScopeMappings                                 []ScopeMapping           `json:"scopeMappings,omitempty"`
	SmtpServer                                    Map                      `json:"smtpServer,omitempty"`
	SslRequired                                   *bool                    `json:"sslRequired,omitempty"`
	SsoSessionIdleTimeout                         int32                    `json:"ssoSessionIdleTimeout,omitempty"`
	SsoSessionIdleTimeoutRememberMe               int32                    `json:"ssoSessionIdleTimeoutRememberMe,omitempty"`
	SsoSessionMaxLifespan                         int32                    `json:"ssoSessionMaxLifespan,omitempty"`
	SsoSessionMaxLifespanRememberMe               int32                    `json:"ssoSessionMaxLifespanRememberMe,omitempty"`
	SupportedLocales                              []string                 `json:"supportedLocales,omitempty"`
	UserFederationMappers                         []UserFederationMapper   `json:"userFederationMappers,omitempty"`
	UserFederationProviders                       []UserFederationProvider `json:"userFederationProviders,omitempty"`
	UserManagedAccessAllowed                      *bool                    `json:"userManagedAccessAllowed,omitempty"`
	Users                                         []User                   `json:"users,omitempty"`
	VerifyEmail                                   *bool                    `json:"verifyEmail,omitempty"`
	WaitIncrementSeconds                          int32                    `json:"waitIncrementSeconds,omitempty"`
	WebAuthnPolicyAcceptableAaguids               []string                 `json:"webAuthnPolicyAcceptableAaguids,omitempty"`
	WebAuthnPolicyAttestationConveyancePreference string                   `json:"webAuthnPolicyAttestationConveyancePreference,omitempty"`
	WebAuthnPolicyAuthenticatorAttachment         string                   `json:"webAuthnPolicyAuthenticatorAttachment,omitempty"`
	WebAuthnPolicyAvoidSameAuthenticatorRegister  *bool                    `json:"webAuthnPolicyAvoidSameAuthenticatorRegister,omitempty"`
	WebAuthnPolicyCreateTimeout                   int32                    `json:"webAuthnPolicyCreateTimeout,omitempty"`
	WebAuthnPolicyRequireResidentKey              string                   `json:"webAuthnPolicyRequireResidentKey,omitempty"`
	WebAuthnPolicyRpEntityName                    string                   `json:"webAuthnPolicyRpEntityName,omitempty"`
	WebAuthnPolicyRpId                            string                   `json:"webAuthnPolicyRpId,omitempty"`
	WebAuthnPolicySignatureAlgorithms             []string                 `json:"webAuthnPolicySignatureAlgorithms,omitempty"`
	WebAuthnPolicyUserVerificationRequirement     string                   `json:"webAuthnPolicyUserVerificationRequirement,omitempty"`
}
